### ISSUE TITLE
Getting an error on "Publish message" action

### ISSUE THREAD

**Issue by hovodab** [redpanda-data/kowl#357]
Docker image: quay.io/cloudhut/kowl@sha256:469fdd85df5e73a731b06404091457d7523f9a8565d639ff571d3256289ad5dc

Message:
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stack (Decoded):
Xg (../node_modules/react-dom/cjs/react-dom.production.min.js:280:176)
d=e(k,f.props);d.ref=Qg (../node_modules/react-dom/cjs/react-dom.production.min.js:149:162)
useOpaqueIdentifier (../node_modules/react-dom/cjs/react-dom.production.min.js:176:170)
d=b.pendingProps;e=b.memoizedState;e=null!==e?e.element:null;yg(a,b);Cg(b,d,null,c);d=b.memoizedState.element;if(d===e)sh(),b=hi(a,b,c);else{e=b.stateNode;if(f=e.hydrate)kh=rf(b.stateNode.containerInfo.firstChild),jh=b,f=lh=!0;if (../node_modules/react-dom/cjs/react-dom.production.min.js:271:133)
Pj (../node_modules/react-dom/cjs/react-dom.production.min.js:250:346)
Pj (../node_modules/react-dom/cjs/react-dom.production.min.js:250:277)
Pj (../node_modules/react-dom/cjs/react-dom.production.min.js:250:137)
Lj (../node_modules/react-dom/cjs/react-dom.production.min.js:243:162)
jg (../node_modules/react-dom/cjs/react-dom.production.min.js:123:114)
unstable_next (../node_modules/scheduler/cjs/scheduler.production.min.js:18:342)

Stack (Raw):
at Gl (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1520967)
    at http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1469157
    at Mi (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1480802)
    at $s (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1526992)
    at _l (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1512343)
    at Cl (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1512271)
    at Sl (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1512134)
    at gl (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1509100)
    at http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1458479
    at t.unstable_runWithPriority (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1535898)

Components:

    at article
    at div
    at l (http://localhost:8092/static/js/main.64d8acba.chunk.js:1:21792)
    at div
    at n (http://localhost:8092/static/js/main.64d8acba.chunk.js:1:492188)
    at div
    at div
    at http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1302380
    at div
    at n (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:134587)
    at http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:134880
    at http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1302523
    at div
    at div
    at O (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1304665)
    at http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:701910
    at n (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1314873)
    at w (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1306861)
    at G (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:293866)
    at l (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:59703)
    at n (http://localhost:8092/static/js/main.64d8acba.chunk.js:1:171539)
    at article
    at div
    at l (http://localhost:8092/static/js/main.64d8acba.chunk.js:1:21792)
    at div
    at n (http://localhost:8092/static/js/main.64d8acba.chunk.js:1:243515)
    at div
    at http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:521021
    at r (http://localhost:8092/static/js/main.64d8acba.chunk.js:1:145237)
    at t (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:123122)
    at t (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:124073)
    at u (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1001204)
    at m (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:1001913)
    at Hi
    at n (http://localhost:8092/static/js/main.64d8acba.chunk.js:1:431287)
    at main
    at m (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:605885)
    at a (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:605715)
    at section
    at http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:606145
    at a (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:605715)
    at l (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:59703)
    at section
    at http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:606145
    at a (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:605715)
    at t (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:123122)
    at t (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:124073)
    at n (http://localhost:8092/static/js/main.64d8acba.chunk.js:1:442593)
    at n (http://localhost:8092/static/js/main.64d8acba.chunk.js:1:474596)
    at t (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:120416)
    at t (http://localhost:8092/static/js/2.b5eb64a6.chunk.js:2:350764)

Environment:
NODE_ENV       : production
GIT_SHA        : 4b16d9b7a1c99235dde2cf312f15a2418833edf4
GIT_REF        : master
TIMESTAMP      : 1650984073
BUILT_FROM_PUSH: true
appName        : Kowl

Location:
Protocol: http:
Path    : /topics/test
Search  : ?o=-1&p=-1&q&s=50
Hash    : #messages

![image](https://user-images.githubusercontent.com/10878742/165993164-d16ae364-31cf-428d-babb-ef62ed7684ba.png)

**Comment by streamtree** [comment]
Same here. I didn't look to see if it's the same output.

Message:
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stack (Decoded):
Xg (../node_modules/react-dom/cjs/react-dom.production.min.js:280:182)
d=e(k,f.props);d.ref=Qg (../node_modules/react-dom/cjs/react-dom.production.min.js:149:165)
useOpaqueIdentifier (../node_modules/react-dom/cjs/react-dom.production.min.js:176:173)
d=b.pendingProps;e=b.memoizedState;e=null!==e?e.element:null;yg(a,b);Cg(b,d,null,c);d=b.memoizedState.element;if(d===e)sh(),b=hi(a,b,c);else{e=b.stateNode;if(f=e.hydrate)kh=rf(b.stateNode.containerInfo.firstChild),jh=b,f=lh=!0;if (../node_modules/react-dom/cjs/react-dom.production.min.js:271:136)
Pj (../node_modules/react-dom/cjs/react-dom.production.min.js:250:349)
Pj (../node_modules/react-dom/cjs/react-dom.production.min.js:250:280)
Pj (../node_modules/react-dom/cjs/react-dom.production.min.js:250:137)
Lj (../node_modules/react-dom/cjs/react-dom.production.min.js:243:165)
gl ([native code]::)
jg (../node_modules/react-dom/cjs/react-dom.production.min.js:123:114)
unstable_next (../node_modules/scheduler/cjs/scheduler.production.min.js:18:342)
jg (../node_modules/react-dom/cjs/react-dom.production.min.js:123:63)
eg (../node_modules/react-dom/cjs/react-dom.production.min.js:122:427)
Hb (../node_modules/react-dom/cjs/react-dom.production.min.js:292:100)
$c (../node_modules/react-dom/cjs/react-dom.production.min.js:73:354)
Xt ([native code]::)

Stack (Raw):
Gl@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1520972
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1469159
Mi@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1480804
$s@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1526994
_l@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1512345
Cl@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1512273
Sl@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1512136
gl@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1509102
gl@[native code]
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1458480
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1535899
Wa@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1458426
$a@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1458361
Pe@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1529710
Xt@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1436985
Xt@[native code]

Components:

article
div
l@http://localhost:8080/static/js/main.64d8acba.chunk.js:1:21791
div
n@http://localhost:8080/static/js/main.64d8acba.chunk.js:1:492188
div
div
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1302379
div
n@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:134587
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:134879
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1302522
div
div
O@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1304664
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:701909
n@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1314873
Dialog@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1306860
G@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:293876
w@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:58776
n@http://localhost:8080/static/js/main.64d8acba.chunk.js:1:171539
article
div
l@http://localhost:8080/static/js/main.64d8acba.chunk.js:1:21791
div
n@http://localhost:8080/static/js/main.64d8acba.chunk.js:1:243515
div
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:521021
r@http://localhost:8080/static/js/main.64d8acba.chunk.js:1:145237
t@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:123127
t@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:124078
u@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1001203
m@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:1001912
Hi
n@http://localhost:8080/static/js/main.64d8acba.chunk.js:1:431287
main
m@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:605884
Content@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:605725
section
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:606155
Layout@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:605725
w@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:58776
section
@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:606155
Layout@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:605725
t@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:123127
t@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:124078
n@http://localhost:8080/static/js/main.64d8acba.chunk.js:1:442593
n@http://localhost:8080/static/js/main.64d8acba.chunk.js:1:474596
t@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:120420
t@http://localhost:8080/static/js/2.b5eb64a6.chunk.js:2:350769

Environment:
NODE_ENV       : production
GIT_SHA        : 4b16d9b7a1c99235dde2cf312f15a2418833edf4
GIT_REF        : master
TIMESTAMP      : 1650984073
BUILT_FROM_PUSH: true
appName        : Kowl

Location:
Protocol: http:
Path    : /topics/http-proxy
Search  : ?o=-1&p=-1&q&s=50
Hash    : #messages

**Comment by weeco** [comment]
Hey @hovodab and @streamtree ,
I just tried to reproduce it - without luck. Could you describe what you've done and when that error message would pop up? I think I tried several combinations (with or without key/value/header/compression etc), but all seemed to work

![screenshot 2022-04-30 at 16 49 32](https://user-images.githubusercontent.com/23424570/166112787-e77a42dc-7aa2-4ffa-9080-7ed10f5fb6b2.png)
 fine

**Comment by hovodab** [comment]
Hello @weeco,
Here are my steps.
1. Run the docker container: `docker run --network=my-network -p 8092:8080 -e KAFKA_BROKERS=kafka:39092 quay.io/cloudhut/kowl@sha256:469fdd85df5e73a731b06404091457d7523f9a8565d639ff571d3256289ad5dc`
2. 
![image](https://user-images.githubusercontent.com/10878742/166194506-51bf0428-f09f-4c90-bc0b-d10ebb41314f.png)
3. Clicking on `Publish Message`
4. 
![image](https://user-images.githubusercontent.com/10878742/166194613-8aa367d3-d5e9-4834-b61e-099cef0cab8a.png)

**Comment by streamtree** [comment]
I followed the exact same steps as @hovodab

Craig

**Comment by nargotik** [comment]
Yes, same issue on docker image on docker-compose

```yaml
version: '3.7'
x-extra_hosts:
  &default-extra_hosts
  - "node0:192.168.1.1"

services:
  kowl-docker:
    container_name: kowl
    image: quay.io/cloudhut/kowl:master
    restart: always
    ports:
       - 80:8080
    environment:
      KAFKA_BROKERS: node0:9092
      KAFKA_SASL_ENABLED: 1
      KAFKA_SASL_USERNAME: admin
      KAFKA_SASL_PASSWORD: admin-password
    extra_hosts: *default-extra_hosts

```

**Comment by weeco** [comment]
Hey all,
we already identified the issue and have a fix ready. However the build pipelines are currently being updated and it may take a while until we can offer a new Docker Image that is available. I'm sorry for that, until then this feature may not be usable. I'm doing my best to get that done as soon as possible.

**Comment by nargotik** [comment]
@weeco Thanks, can you please provide a fix for who want to build a new docker image ? or Building the DockerFile on master solves that ?

**Comment by rikimaru0345** [comment]
@nargotik 
Yes, if you compile the newest commit on the master branch (which at the time of writing is edb20f8d876326b6d8228178416e2febd1af5da8), the issue **should** be fixed.
