### ISSUE TITLE
Preview fields are not displayed in the specified order.

### ISSUE THREAD

**Issue by streamtree** [redpanda-data/kowl#358]
When using preview fields, the definition dialog allows the fields to be dragged and dropped into a particular order. This order is ignored in the UI and some kind of preset order is used instead.

**Comment by rikimaru0345** [comment]
should now be fixed in 905ce28489bf0e46ab349a12da837ac2767ce5ad

thanks for reporting!

**Comment by rikimaru0345** [comment]
please let me know if it works for you as intended now 😄
