### ISSUE TITLE
Wrong timestamps for records when LogAppendTime is used

### ISSUE THREAD

**Issue by brunsgaard** [redpanda-data/kowl#374]
The Kowl UI shows wrong timestamps when LogAppendTime is used and producers produce records with custom create timestamp.

Fixed in franz-go v1.6.0 with this commit https://github.com/twmb/franz-go/commit/a23a076629f395a572e026322ca7feec39708e0d

Please update the franz-go dependency.

cc: @twmb @duedal @tobiasbrodersen

**Comment by weeco** [comment]
Thanks @brunsgaard ,
I've updated the library without verifying whether it's fixed.

Docker builds are currently not available until I fixed the build pipeline, but I plan to do that within the next few days. You can build and push the Docker image on your own nonetheless
